// ATP Player Database - Auto-generated by scrape_atp.py
// Source: github.com/JeffSackmann/tennis_atp (Creative Commons)
// Generated: 2026-08-31 11:55
// Total players: 37
//
// Compact format: [name, country, {ao,rg,w,uso}, titles, careerWins, bestPrizeSeason$, flags, hand, decades[], peakRanking, ext?]
// flags bitmask: 1=yearEndNo1, 2=olympicGold, 4=davisCup, 8=atpFinals, 16=active
// ext keys: m1000=masters titles, wks1=weeks at #1, ht=height(cm), cw=clay wins, hw=hard wins, gw=grass wins, ar=ace rate, aft=age first title, alt=age last title, cl=career length

const PLAYER_DATA = [
  ["Alejandro Tabilo","Chile",{ao:0,rg:0,w:0,uso:0},1,13,0,16,"L",[2020],9999,{cw:3,hw:10,ar:8.6,cl:2}],
  ["Alex de Minaur","Australia",{ao:0,rg:0,w:0,uso:0},1,59,0,20,"R",[2020],9999,{cw:10,hw:46,gw:3,ar:6.3,cl:2}],
  ["Alexander Bublik","Kazakhstan",{ao:0,rg:0,w:0,uso:0},5,41,0,16,"R",[2020],9999,{cw:16,hw:20,gw:5,ar:16.5,cl:2}],
  ["Alexander Zverev","Germany",{ao:0,rg:0,w:0,uso:0},1,59,0,18,"R",[2020],9999,{cw:18,hw:35,gw:6,ar:10.9,cl:2}],
  ["Alexandre Muller","France",{ao:0,rg:0,w:0,uso:0},1,25,0,16,"R",[2020],9999,{cw:11,hw:14,ar:5.2,cl:2}],
  ["Andrey Rublev","Russia",{ao:0,rg:0,w:0,uso:0},1,38,0,20,"R",[2020],9999,{cw:10,hw:24,gw:4,ar:11.7,cl:2}],
  ["Ben Shelton","USA",{ao:0,rg:0,w:0,uso:0},1,42,0,16,"L",[2020],9999,{m1000:1,cw:8,hw:28,gw:6,ar:12.4,cl:2}],
  ["Carlos Alcaraz","Spain",{ao:1,rg:1,w:2,uso:1},8,71,0,16,"R",[2020],9999,{m1000:3,cw:22,hw:38,gw:11,ar:7.4}],
  ["Casper Ruud","Norway",{ao:0,rg:0,w:0,uso:0},2,40,0,16,"R",[2020],9999,{m1000:1,cw:14,hw:26,ar:8.9,cl:2}],
  ["Daniil Medvedev","Russia",{ao:0,rg:0,w:0,uso:0},2,48,0,20,"R",[2020],9999,{cw:7,hw:36,gw:5,ar:12.0,cl:2}],
  ["Denis Shapovalov","Canada",{ao:0,rg:0,w:0,uso:0},2,26,0,16,"L",[2020],9999,{cw:2,hw:23,gw:1,ar:12.2,cl:2}],
  ["Felix Auger-Aliassime","Canada",{ao:0,rg:0,w:0,uso:0},3,52,0,16,"R",[2020],9999,{cw:3,hw:43,gw:6,ar:14.7,cl:2}],
  ["Flavio Cobolli","Italy",{ao:0,rg:0,w:0,uso:0},2,35,0,20,"R",[2020],9999,{cw:14,hw:15,gw:6,ar:6.2,cl:2}],
  ["Gabriel Diallo","Canada",{ao:0,rg:0,w:0,uso:0},1,31,0,16,"R",[2020],9999,{cw:6,hw:16,gw:9,ar:11.9,cl:2}],
  ["Gael Monfils","France",{ao:0,rg:0,w:0,uso:0},1,18,0,20,"R",[2020],9999,{cw:3,hw:14,gw:1,ar:12.6,cl:2}],
  ["Holger Rune","Denmark",{ao:0,rg:0,w:0,uso:0},1,36,0,16,"R",[2020],9999,{cw:10,hw:24,gw:2,ar:7.4}],
  ["Hubert Hurkacz","Poland",{ao:0,rg:0,w:0,uso:0},1,19,0,16,"R",[2020],9999,{cw:7,hw:11,gw:1,ar:19.0,cl:2}],
  ["Jack Draper","United Kingdom",{ao:0,rg:0,w:0,uso:0},1,30,0,16,"L",[2020],9999,{m1000:1,cw:12,hw:14,gw:4,ar:10.8}],
  ["Jakub Mensik","Czech Republic",{ao:0,rg:0,w:0,uso:0},2,39,0,16,"R",[2020],9999,{m1000:1,cw:6,hw:29,gw:4,ar:18.5,cl:2}],
  ["Jannik Sinner","Italy",{ao:2,rg:0,w:0,uso:1},6,58,0,28,"R",[2020],9999,{m1000:1,cw:11,hw:39,gw:8,ar:9.4}],
  ["Jenson Brooksby","USA",{ao:0,rg:0,w:0,uso:0},1,22,0,16,"R",[2020],9999,{cw:6,hw:11,gw:5,ar:4.5,cl:2}],
  ["Jiri Lehecka","Czech Republic",{ao:0,rg:0,w:0,uso:0},1,42,0,16,"R",[2020],9999,{cw:5,hw:30,gw:7,ar:13.1,cl:2}],
  ["Joao Fonseca","Brazil",{ao:0,rg:0,w:0,uso:0},2,27,0,16,"R",[2020],9999,{cw:8,hw:16,gw:3,ar:8.0}],
  ["Laslo Djere","Serbia",{ao:0,rg:0,w:0,uso:0},1,13,0,16,"R",[2020],9999,{cw:7,hw:5,gw:1,ar:9.0,cl:2}],
  ["Learner Tien","USA",{ao:0,rg:0,w:0,uso:0},2,37,0,16,"L",[2020],9999,{cw:1,hw:32,gw:4,ar:6.2,cl:2}],
  ["Luciano Darderi","Italy",{ao:0,rg:0,w:0,uso:0},3,30,0,16,"R",[2020],9999,{cw:21,hw:7,gw:2,ar:9.5,cl:2}],
  ["Marton Fucsovics","Hungary",{ao:0,rg:0,w:0,uso:0},1,21,0,16,"R",[2020],9999,{cw:6,hw:11,gw:4,ar:5.9,cl:2}],
  ["Miomir Kecmanovic","Serbia",{ao:0,rg:0,w:0,uso:0},1,25,0,16,"R",[2020],9999,{cw:2,hw:21,gw:2,ar:8.6,cl:2}],
  ["Novak Djokovic","Serbia",{ao:0,rg:0,w:0,uso:0},2,39,0,22,"R",[2020],9999,{cw:9,hw:25,gw:5,ar:10.9}],
  ["Sebastian Baez","Argentina",{ao:0,rg:0,w:0,uso:0},1,24,0,16,"R",[2020],9999,{cw:11,hw:13,ar:3.1,cl:2}],
  ["Stefanos Tsitsipas","Greece",{ao:0,rg:0,w:0,uso:0},1,25,0,16,"R",[2020],9999,{cw:7,hw:17,gw:1,ar:9.2,cl:2}],
  ["Tallon Griekspoor","Netherlands",{ao:0,rg:0,w:0,uso:0},1,30,0,16,"R",[2020],9999,{cw:11,hw:15,gw:4,ar:10.8,cl:2}],
  ["Taylor Fritz","USA",{ao:0,rg:0,w:0,uso:0},3,54,0,16,"R",[2020],9999,{cw:3,hw:38,gw:13,ar:15.7,cl:2}],
  ["Tomas Machac","Czech Republic",{ao:0,rg:0,w:0,uso:0},2,28,0,16,"R",[2020],9999,{cw:2,hw:23,gw:3,ar:9.2,cl:2}],
  ["Ugo Humbert","France",{ao:0,rg:0,w:0,uso:0},1,29,0,16,"L",[2020],9999,{cw:2,hw:23,gw:4,ar:10.1,cl:2}],
  ["Valentin Vacherot","Monaco",{ao:0,rg:0,w:0,uso:0},1,17,0,16,"R",[2020],9999,{m1000:1,cw:3,hw:14,ar:9.6,cl:2}],
  ["Rohan Cameron","New Zealand",{ao:0,rg:0,w:0,uso:0},0,0,0,16,"R",[2020],1500],
];


// Filter out duplicates and invalid entries
const validPlayerData = PLAYER_DATA.filter(p =>
  p[0] && p[1] && p[8] && p[8].length > 0
);

// Remove exact duplicate names
const seenNames = new Set();
const uniquePlayerData = validPlayerData.filter(p => {
  const name = p[0];
  if (seenNames.has(name)) return false;
  seenNames.add(name);
  return true;
});

// Parse compact data into full player objects
const PLAYERS = uniquePlayerData.map((p, idx) => {
  const flags = p[6];
  const ext = p[10] || {};
  return {
    id: p[0].toLowerCase().replace(/[^a-z0-9]/g, '_'),
    name: p[0],
    country: p[1],
    grandSlams: p[2],
    titles: p[3],
    careerWins: p[4],
    bestPrizeMoneySeason: p[5],
    yearEndNo1: !!(flags & 1),
    olympicSinglesGold: !!(flags & 2),
    davisCup: !!(flags & 4),
    atpFinals: !!(flags & 8),
    active: !!(flags & 16),
    hand: p[7],
    decades: p[8],
    peakRanking: p[9],
    masters1000: ext.m1000 || 0,
    weeksAtNo1: ext.wks1 || 0,
    heightCm: ext.ht || 0,
    clayWins: ext.cw || 0,
    hardWins: ext.hw || 0,
    grassWins: ext.gw || 0,
    aceRate: ext.ar || 0,
    ageFirstTitle: ext.aft || 0,
    ageLastTitle: ext.alt || 0,
    careerLength: ext.cl || 0,
    photoUrl: getPlayerPhotoUrl(p[0])
  };
});

// Player photo URL
function getPlayerPhotoUrl(name) {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&size=120&background=2d6a4f&color=fff&bold=true&format=svg`;
}

// Helper to get country flag emoji
function getCountryFlag(country) {
  const flags = {
    "USA": "\ud83c\uddfa\ud83c\uddf8", "Spain": "\ud83c\uddea\ud83c\uddf8", "Switzerland": "\ud83c\udde8\ud83c\udded",
    "Serbia": "\ud83c\uddf7\ud83c\uddf8", "United Kingdom": "\ud83c\uddec\ud83c\udde7", "France": "\ud83c\uddeb\ud83c\uddf7",
    "Germany": "\ud83c\udde9\ud83c\uddea", "Australia": "\ud83c\udde6\ud83c\uddfa", "Argentina": "\ud83c\udde6\ud83c\uddf7",
    "Sweden": "\ud83c\uddf8\ud83c\uddea", "Russia": "\ud83c\uddf7\ud83c\uddfa", "Czech Republic": "\ud83c\udde8\ud83c\uddff",
    "Croatia": "\ud83c\udded\ud83c\uddf7", "Austria": "\ud83c\udde6\ud83c\uddf9", "Italy": "\ud83c\uddee\ud83c\uddf9",
    "Chile": "\ud83c\udde8\ud83c\uddf1", "Brazil": "\ud83c\udde7\ud83c\uddf7", "Netherlands": "\ud83c\uddf3\ud83c\uddf1",
    "Japan": "\ud83c\uddef\ud83c\uddf5", "Canada": "\ud83c\udde8\ud83c\udde6", "Greece": "\ud83c\uddec\ud83c\uddf7",
    "Norway": "\ud83c\uddf3\ud83c\uddf4", "Poland": "\ud83c\uddf5\ud83c\uddf1", "Bulgaria": "\ud83c\udde7\ud83c\uddec",
    "Belgium": "\ud83c\udde7\ud83c\uddea", "South Africa": "\ud83c\uddff\ud83c\udde6", "Romania": "\ud83c\uddf7\ud83c\uddf4",
    "Ecuador": "\ud83c\uddea\ud83c\udde8", "Latvia": "\ud83c\uddf1\ud83c\uddfb", "Denmark": "\ud83c\udde9\ud83c\uddf0",
    "Finland": "\ud83c\uddeb\ud83c\uddee", "Georgia": "\ud83c\uddec\ud83c\uddea", "Kazakhstan": "\ud83c\uddf0\ud83c\uddff",
    "Portugal": "\ud83c\uddf5\ud83c\uddf9", "Ukraine": "\ud83c\uddfa\ud83c\udde6", "India": "\ud83c\uddee\ud83c\uddf3",
    "Mexico": "\ud83c\uddf2\ud83c\uddfd", "Uruguay": "\ud83c\uddfa\ud83c\uddfe", "South Korea": "\ud83c\uddf0\ud83c\uddf7",
    "Thailand": "\ud83c\uddf9\ud83c\udded", "Cyprus": "\ud83c\udde8\ud83c\uddfe", "Zimbabwe": "\ud83c\uddff\ud83c\uddfc",
    "Hungary": "\ud83c\udded\ud83c\uddfa", "China": "\ud83c\udde8\ud83c\uddf3",
    "Bosnia and Herzegovina": "\ud83c\udde7\ud83c\udde6",
    "New Zealand": "\ud83c\uddf3\ud83c\uddff", "Hong Kong": "\ud83c\udded\ud83c\uddf0",
    "Tunisia": "\ud83c\uddf9\ud83c\uddf3", "Colombia": "\ud83c\udde8\ud83c\uddf4",
    "Dominican Republic": "\ud83c\udde9\ud83c\uddf4", "Jamaica": "\ud83c\uddef\ud83c\uddf2",
    "Taiwan": "\ud83c\uddf9\ud83c\uddfc", "Uzbekistan": "\ud83c\uddfa\ud83c\uddff",
    "Slovenia": "\ud83c\uddf8\ud83c\uddee", "Slovakia": "\ud83c\uddf8\ud83c\uddf0",
    "Moldova": "\ud83c\uddf2\ud83c\udde9", "Belarus": "\ud83c\udde7\ud83c\uddfe",
    "Morocco": "\ud83c\uddf2\ud83c\udde6", "Israel": "\ud83c\uddee\ud83c\uddf1",
    "Turkey": "\ud83c\uddf9\ud83c\uddf7", "Ireland": "\ud83c\uddee\ud83c\uddea",
    "Luxembourg": "\ud83c\uddf1\ud83c\uddfa", "Monaco": "\ud83c\uddf2\ud83c\udde8",
    "Lithuania": "\ud83c\uddf1\ud83c\uddf9", "Estonia": "\ud83c\uddea\ud83c\uddea",
    "Peru": "\ud83c\uddf5\ud83c\uddea", "Venezuela": "\ud83c\uddfb\ud83c\uddea",
    "Paraguay": "\ud83c\uddf5\ud83c\uddfe", "Bolivia": "\ud83c\udde7\ud83c\uddf4",
    "Puerto Rico": "\ud83c\uddf5\ud83c\uddf7", "Pakistan": "\ud83c\uddf5\ud83c\uddf0",
    "Egypt": "\ud83c\uddea\ud83c\uddec",
  };
  return flags[country] || "\ud83c\udff3\ufe0f";
}
