// Player photos from Wikipedia/Wikimedia Commons (CC-BY-SA)
// Auto-generated by scrape_photos.py
const PLAYER_PHOTOS = {
  "alexander_bublik": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Sascha_Bublik_%282023_DC_Open%29_05_%28cropped%29.jpg/250px-Sascha_Bublik_%282023_DC_Open%29_05_%28cropped%29.jpg",
  "alexander_zverev": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Alexander_Zverev.jpg/250px-Alexander_Zverev.jpg",
  "alexandre_muller": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Muller_RGQ22_%2837%29_%2852129571758%29.jpg/250px-Muller_RGQ22_%2837%29_%2852129571758%29.jpg",
  "andrey_rublev": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Andrey_Rublev_%282023_US_Open%29_02_%28cropped%29.jpg/250px-Andrey_Rublev_%282023_US_Open%29_02_%28cropped%29.jpg",
  "carlos_alcaraz": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Carlos_Alcaraz_2025_FO.jpg/250px-Carlos_Alcaraz_2025_FO.jpg",
  "casper_ruud": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Ruud_RG22_%2858%29_%2852144535415%29.jpg/250px-Ruud_RG22_%2858%29_%2852144535415%29.jpg",
  "daniil_medvedev": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Danill_Medvedev_Miami_2019_%28cropped%29.jpg/250px-Danill_Medvedev_Miami_2019_%28cropped%29.jpg",
  "denis_shapovalov": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Denis_Shapovalov%2C_Swiss_Indoors_Basel_2025_%28cropped%29.jpg/250px-Denis_Shapovalov%2C_Swiss_Indoors_Basel_2025_%28cropped%29.jpg",
  "gabriel_diallo": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Diallo_WMQ23_%2853061896439%29.jpg/250px-Diallo_WMQ23_%2853061896439%29.jpg",
  "holger_rune": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Rune_RG22_%284%29_%2852144534990%29.jpg/250px-Rune_RG22_%284%29_%2852144534990%29.jpg",
  "jakub_mensik": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Jakub_Men%C5%A1%C3%ADk_%282023_US_Open%29_14_%28cropped%29.jpg/250px-Jakub_Men%C5%A1%C3%ADk_%282023_US_Open%29_14_%28cropped%29.jpg",
  "jannik_sinner": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Jannik_Sinner_2025_US_Open.jpg/250px-Jannik_Sinner_2025_US_Open.jpg",
  "jenson_brooksby": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Brooksby_RG21_%2842%29_%2851376192761%29.jpg/250px-Brooksby_RG21_%2842%29_%2851376192761%29.jpg",
  "jiri_lehecka": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Lehecka_MCM23_%285%29_%2852883527310%29.jpg/250px-Lehecka_MCM23_%285%29_%2852883527310%29.jpg",
  "marton_fucsovics": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/M%C3%A1rton_Fucsovics_%282023_US_Open%29_01_%28cropped%29.jpg/250px-M%C3%A1rton_Fucsovics_%282023_US_Open%29_01_%28cropped%29.jpg",
  "miomir_kecmanovic": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Kecmanovic_RG21_%2811%29_%2851377164760%29.jpg/250px-Kecmanovic_RG21_%2811%29_%2851377164760%29.jpg",
  "novak_djokovic": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Novak_Djokovic_2024_Paris_Olympics.jpg/250px-Novak_Djokovic_2024_Paris_Olympics.jpg",
  "sebastian_baez": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Baez_RG22_%28cropped%29.jpg/250px-Baez_RG22_%28cropped%29.jpg",
  "stefanos_tsitsipas": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tsitsipas_S._MCM22_%28cropped%29.jpg/250px-Tsitsipas_S._MCM22_%28cropped%29.jpg",
  "tallon_griekspoor": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Griekspoor_RG22_%281%29_%2852144112028%29.jpg/250px-Griekspoor_RG22_%281%29_%2852144112028%29.jpg",
  "taylor_fritz": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Taylor_Fritz_-_Delray_Beach_Open_Final_Round_%28cropped%29.jpg/250px-Taylor_Fritz_-_Delray_Beach_Open_Final_Round_%28cropped%29.jpg",
  "tomas_machac": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Machac_WMQ23_%2853062093175%29.jpg/250px-Machac_WMQ23_%2853062093175%29.jpg"
};
