#!/usr/bin/env python3
"""
Scrape player photos from Wikipedia/Wikimedia Commons.

Reads player names from js/players.js, queries the Wikipedia API for
thumbnail images, caches results, and generates js/player-photos.js.

Uses only Python stdlib. No external dependencies.
"""

import json
import os
import re
import time
import urllib.request
import urllib.parse
import urllib.error

# Paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
PLAYERS_JS = os.path.join(PROJECT_DIR, "js", "players.js")
CACHE_FILE = os.path.join(SCRIPT_DIR, "player_photos.json")
OUTPUT_JS = os.path.join(PROJECT_DIR, "js", "player-photos.js")

WIKI_API = "https://en.wikipedia.org/w/api.php"
THUMB_SIZE = 200
REQUEST_DELAY = 0.5  # 500ms between requests (Wikipedia rate limit)


def parse_player_names(filepath):
    """Parse player names from the PLAYER_DATA array in players.js.

    Matches lines like: ["Andre Agassi","USA",{...
    Returns a list of player name strings.
    """
    names = []
    pattern = re.compile(r'^\s*\["([^"]+)",')
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            m = pattern.match(line)
            if m:
                names.append(m.group(1))
    return names


def name_to_id(name):
    """Convert a player name to a lowercase underscore-separated ID.

    Same logic as the app's ID generation: lowercase, replace
    non-alphanumeric characters with underscores.
    """
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def fetch_wiki_thumbnail(title):
    """Query the Wikipedia API for a page thumbnail URL.

    Returns the thumbnail URL string, or None if not found.
    """
    params = urllib.parse.urlencode({
        "action": "query",
        "titles": title,
        "prop": "pageimages",
        "format": "json",
        "pithumbsize": THUMB_SIZE,
        "redirects": 1,
    })
    url = f"{WIKI_API}?{params}"

    req = urllib.request.Request(url, headers={
        "User-Agent": "TennisGridBot/1.0 (player photo scraper; educational project)"
    })

    max_retries = 5
    for attempt in range(max_retries):
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            break
        except urllib.error.HTTPError as e:
            if e.code == 429:
                retry_after = int(e.headers.get("Retry-After", "2"))
                sleep_for = retry_after * (2 ** attempt)
                print(f"  Rate limited, retrying in {sleep_for}s...")
                time.sleep(sleep_for)
                continue
            raise RuntimeError(f"API request failed for '{title}': {e}")
        except (urllib.error.URLError, OSError, json.JSONDecodeError) as e:
            raise RuntimeError(f"API request failed for '{title}': {e}")
    else:
        raise RuntimeError(f"Exceeded retries for '{title}' due to rate limiting")

    pages = data.get("query", {}).get("pages", {})
    for page in pages.values():
        thumb = page.get("thumbnail", {}).get("source")
        if thumb:
            return thumb

    return None


def get_photo_url(player_name):
    """Try to get a Wikipedia photo for a player.

    First tries the exact name. If that yields no thumbnail, retries
    with '(tennis)' disambiguation suffix.
    """
    # First attempt: exact name
    thumb = fetch_wiki_thumbnail(player_name)
    if thumb:
        return thumb

    # Second attempt: with tennis disambiguation
    thumb = fetch_wiki_thumbnail(f"{player_name} (tennis)")
    return thumb


def load_cache(filepath):
    """Load the JSON cache file. Returns an empty dict if not found."""
    if os.path.exists(filepath):
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                return json.load(f)
        except (json.JSONDecodeError, OSError):
            print(f"Warning: Could not read cache file, starting fresh.")
    return {}


def save_cache(filepath, cache):
    """Write the cache dict to a JSON file."""
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False)


def generate_js(output_path, photo_map):
    """Write the player-photos.js output file."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Player photos from Wikipedia/Wikimedia Commons (CC-BY-SA)\n")
        f.write("// Auto-generated by scrape_photos.py\n")
        f.write("const PLAYER_PHOTOS = {\n")

        entries = sorted(photo_map.items())
        for i, (player_id, url) in enumerate(entries):
            comma = "," if i < len(entries) - 1 else ""
            # Escape any quotes in the URL (unlikely but safe)
            safe_url = url.replace("\\", "\\\\").replace('"', '\\"')
            f.write(f'  "{player_id}": "{safe_url}"{comma}\n')

        f.write("};\n")


def main():
    print("=== Tennis Player Photo Scraper ===\n")

    # Step 1: Parse player names
    print(f"Reading players from {PLAYERS_JS}...")
    player_names = parse_player_names(PLAYERS_JS)
    print(f"Found {len(player_names)} players.\n")

    if not player_names:
        print("Error: No players found. Check the players.js file.")
        return

    # Step 2: Load cache
    cache = load_cache(CACHE_FILE)
    cached_count = sum(1 for name in player_names if name in cache)
    print(f"Cache: {cached_count} players already cached, {len(player_names) - cached_count} to fetch.\n")

    # Step 3: Fetch photos for uncached players
    # Limit to first N players if --limit flag is passed
    import sys
    max_players = len(player_names)
    for arg in sys.argv[1:]:
        if arg.startswith("--limit="):
            max_players = int(arg.split("=")[1])
            print(f"Limiting to first {max_players} players.\n")

    fetched = 0
    errors = 0
    for i, name in enumerate(player_names[:max_players]):
        if name in cache:
            continue

        try:
            url = get_photo_url(name)
            # Cache both hits and misses (None means no photo found)
            cache[name] = url
            fetched += 1

            if url:
                status = "found"
            else:
                status = "no photo"

        except Exception as e:
            print(f"  Error for '{name}': {e}")
            cache[name] = None
            errors += 1

        # Progress reporting every 100 players processed (fetched + errors)
        total_processed = fetched + errors
        if total_processed % 100 == 0 and total_processed > 0:
            print(f"  Progress: {total_processed} players fetched "
                  f"({fetched - errors} ok, {errors} errors)... "
                  f"[{i + 1}/{max_players} total]")

        # Rate limit
        time.sleep(REQUEST_DELAY)

    # Save cache after fetching
    save_cache(CACHE_FILE, cache)
    print(f"\nFetching complete. {fetched} new lookups, {errors} errors.")
    print(f"Cache saved to {CACHE_FILE}\n")

    # Step 4: Build photo map and generate JS
    photo_map = {}
    photos_found = 0
    for name in player_names:
        url = cache.get(name)
        if url:
            player_id = name_to_id(name)
            photo_map[player_id] = url
            photos_found += 1

    generate_js(OUTPUT_JS, photo_map)

    # Step 5: Summary
    total = len(player_names)
    coverage = (photos_found / total * 100) if total > 0 else 0
    print("=== Summary ===")
    print(f"  Total players:    {total}")
    print(f"  Photos found:     {photos_found}")
    print(f"  No photo:         {total - photos_found}")
    print(f"  Coverage:         {coverage:.1f}%")
    print(f"  Output written:   {OUTPUT_JS}")


if __name__ == "__main__":
    main()
